### ISSUE TITLE
Database refill error

### ISSUE THREAD

**Issue by florianh12** [QuirkyCroissant/Queensman_Agency_Application#1]
Couldn't refill database. Got the following error:
```text
frontend_php | Traceback (most recent call last):
frontend_php |   File "/var/www/html/Queensman_imse_Insert.py", line 6, in <module>
frontend_php |     import pandas as pd
frontend_php |   File "/usr/local/lib/python3.9/dist-packages/pandas/__init__.py", line 22, in <module>
frontend_php |     from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
frontend_php |   File "/usr/local/lib/python3.9/dist-packages/pandas/compat/__init__.py", line 18, in <module>
frontend_php |     from pandas.compat.numpy import (
frontend_php |   File "/usr/local/lib/python3.9/dist-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
frontend_php |     from pandas.util.version import Version
frontend_php |   File "/usr/local/lib/python3.9/dist-packages/pandas/util/__init__.py", line 2, in <module>
frontend_php |     from pandas.util._decorators import (  # noqa:F401
frontend_php |   File "/usr/local/lib/python3.9/dist-packages/pandas/util/_decorators.py", line 14, in <module>
frontend_php |     from pandas._libs.properties import cache_readonly
frontend_php |   File "/usr/local/lib/python3.9/dist-packages/pandas/_libs/__init__.py", line 13, in <module>
frontend_php |     from pandas._libs.interval import Interval
frontend_php |   File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
frontend_php | ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by QuirkyCroissant** [comment]
Thank you for reporting the bug. 

Issue should now be resolved, by adding a compatable numpy version into the requirements (which was previously missing)
